trigger: none # This pipeline should only be run manually

pool:
  vmImage: "ubuntu-latest"

variables:
  # --- Terraform State Backend Configuration ---
  tf_backend_resource_group: "rg-terraform-state"
  tf_backend_storage_account: "tfstate12072025"
  tf_backend_container: "tfstate"
  tf_backend_key: "todo.tfstate"

  # --- Service Connection ---
  serviceConnection: "sp-deploy"

stages:
  - stage: Infrastructure
    displayName: "Deploy Infrastructure"
    jobs:
      - job: Terraform
        displayName: "Terraform Apply"
        steps:
          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: "1.9.0"

          - task: TerraformTaskV4@4
            displayName: "Terraform Init"
            inputs:
              provider: "azurerm"
              command: "init"
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform"
              backendServiceArm: $(serviceConnection)
              backendAzureRmResourceGroupName: $(tf_backend_resource_group)
              backendAzureRmStorageAccountName: $(tf_backend_storage_account)
              backendAzureRmContainerName: $(tf_backend_container)
              backendAzureRmKey: $(tf_backend_key)

          - task: TerraformTaskV4@4
            displayName: "Terraform Plan"
            inputs:
              provider: "azurerm"
              command: "plan"
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform"
              environmentServiceNameAzureRM: $(serviceConnection)
              commandOptions: '-var="sql_admin_password=$(SQL_PASSWORD)"'

          - task: TerraformTaskV4@4
            displayName: "Terraform Apply"
            inputs:
              provider: "azurerm"
              command: "apply"
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform"
              commandOptions: '-var="sql_admin_password=$(SQL_PASSWORD)" -auto-approve'
              environmentServiceNameAzureRM: $(serviceConnection)
